package com.lovemoin.card.app.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lovemoin.card.app.db.CardInfo;
import com.lovemoin.card.app.db.MerchantInfo;
import com.lovemoin.card.app.db.ImageInfo;
import com.lovemoin.card.app.db.StoreInfo;
import com.lovemoin.card.app.db.ActivityInfo;
import com.lovemoin.card.app.db.GiftPackInfo;

import com.lovemoin.card.app.db.CardInfoDao;
import com.lovemoin.card.app.db.MerchantInfoDao;
import com.lovemoin.card.app.db.ImageInfoDao;
import com.lovemoin.card.app.db.StoreInfoDao;
import com.lovemoin.card.app.db.ActivityInfoDao;
import com.lovemoin.card.app.db.GiftPackInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardInfoDaoConfig;
    private final DaoConfig merchantInfoDaoConfig;
    private final DaoConfig imageInfoDaoConfig;
    private final DaoConfig storeInfoDaoConfig;
    private final DaoConfig activityInfoDaoConfig;
    private final DaoConfig giftPackInfoDaoConfig;

    private final CardInfoDao cardInfoDao;
    private final MerchantInfoDao merchantInfoDao;
    private final ImageInfoDao imageInfoDao;
    private final StoreInfoDao storeInfoDao;
    private final ActivityInfoDao activityInfoDao;
    private final GiftPackInfoDao giftPackInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardInfoDaoConfig = daoConfigMap.get(CardInfoDao.class).clone();
        cardInfoDaoConfig.initIdentityScope(type);

        merchantInfoDaoConfig = daoConfigMap.get(MerchantInfoDao.class).clone();
        merchantInfoDaoConfig.initIdentityScope(type);

        imageInfoDaoConfig = daoConfigMap.get(ImageInfoDao.class).clone();
        imageInfoDaoConfig.initIdentityScope(type);

        storeInfoDaoConfig = daoConfigMap.get(StoreInfoDao.class).clone();
        storeInfoDaoConfig.initIdentityScope(type);

        activityInfoDaoConfig = daoConfigMap.get(ActivityInfoDao.class).clone();
        activityInfoDaoConfig.initIdentityScope(type);

        giftPackInfoDaoConfig = daoConfigMap.get(GiftPackInfoDao.class).clone();
        giftPackInfoDaoConfig.initIdentityScope(type);

        cardInfoDao = new CardInfoDao(cardInfoDaoConfig, this);
        merchantInfoDao = new MerchantInfoDao(merchantInfoDaoConfig, this);
        imageInfoDao = new ImageInfoDao(imageInfoDaoConfig, this);
        storeInfoDao = new StoreInfoDao(storeInfoDaoConfig, this);
        activityInfoDao = new ActivityInfoDao(activityInfoDaoConfig, this);
        giftPackInfoDao = new GiftPackInfoDao(giftPackInfoDaoConfig, this);

        registerDao(CardInfo.class, cardInfoDao);
        registerDao(MerchantInfo.class, merchantInfoDao);
        registerDao(ImageInfo.class, imageInfoDao);
        registerDao(StoreInfo.class, storeInfoDao);
        registerDao(ActivityInfo.class, activityInfoDao);
        registerDao(GiftPackInfo.class, giftPackInfoDao);
    }
    
    public void clear() {
        cardInfoDaoConfig.getIdentityScope().clear();
        merchantInfoDaoConfig.getIdentityScope().clear();
        imageInfoDaoConfig.getIdentityScope().clear();
        storeInfoDaoConfig.getIdentityScope().clear();
        activityInfoDaoConfig.getIdentityScope().clear();
        giftPackInfoDaoConfig.getIdentityScope().clear();
    }

    public CardInfoDao getCardInfoDao() {
        return cardInfoDao;
    }

    public MerchantInfoDao getMerchantInfoDao() {
        return merchantInfoDao;
    }

    public ImageInfoDao getImageInfoDao() {
        return imageInfoDao;
    }

    public StoreInfoDao getStoreInfoDao() {
        return storeInfoDao;
    }

    public ActivityInfoDao getActivityInfoDao() {
        return activityInfoDao;
    }

    public GiftPackInfoDao getGiftPackInfoDao() {
        return giftPackInfoDao;
    }

}
