package com.lovemoin.card.app.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.lovemoin.card.app.constant.Config;
import org.json.JSONException;
import org.json.JSONObject;
// KEEP INCLUDES END
/**
 * Entity mapped to table "GIFT_PACK_INFO".
 */
public class GiftPackInfo implements java.io.Serializable {

    private String giftId;
    private Integer priority;
    private String comment;
    private Boolean ignore;
    private Boolean needCode;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GiftPackInfo() {
    }

    public GiftPackInfo(String giftId) {
        this.giftId = giftId;
    }

    public GiftPackInfo(String giftId, Integer priority, String comment, Boolean ignore, Boolean needCode) {
        this.giftId = giftId;
        this.priority = priority;
        this.comment = comment;
        this.ignore = ignore;
        this.needCode = needCode;
    }

    public String getGiftId() {
        return giftId;
    }

    public void setGiftId(String giftId) {
        this.giftId = giftId;
    }

    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Boolean getIgnore() {
        return ignore;
    }

    public void setIgnore(Boolean ignore) {
        this.ignore = ignore;
    }

    public Boolean getNeedCode() {
        return needCode;
    }

    public void setNeedCode(Boolean needCode) {
        this.needCode = needCode;
    }

    // KEEP METHODS - put your custom methods here
    public GiftPackInfo(JSONObject jsonObject) throws JSONException {
        giftId = jsonObject.getString(Config.KEY_GIFT_ID);
        priority = jsonObject.getInt(Config.KEY_GIFT_PRIORITY);
        comment = jsonObject.getString(Config.KEY_GIFT_COMMENT);
        ignore = jsonObject.getInt(Config.KEY_GIFT_IGNORE)==1;
        needCode = jsonObject.getInt(Config.KEY_NEED_CODE)==1;
    }
    // KEEP METHODS END

}
