package com.lovemoin.card.app.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "IGNORED_AD_INFO".
 */
public class IgnoredAdInfo implements java.io.Serializable {

    private String activityId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IgnoredAdInfo() {
    }

    public IgnoredAdInfo(String activityId) {
        this.activityId = activityId;
    }

    public String getActivityId() {
        return activityId;
    }

    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
